# -*- coding: utf-8 -*-
"""MonteCarlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DvAJw4Q4Arcp0Aj2gfEaw8VuNZWZYam-
"""

# ══════════════════════════════════════════════════════════════════════════════
# CELDA 1 — LIBRERÍAS
# ══════════════════════════════════════════════════════════════════════════════
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.patches as mpatches
from scipy import stats
from scipy.stats import norm
import warnings
warnings.filterwarnings('ignore')

plt.rcParams['figure.figsize']    = (14, 7)
plt.rcParams['font.family']       = 'Arial'
plt.rcParams['axes.spines.top']   = False
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.grid']         = True
plt.rcParams['grid.alpha']        = 0.3

np.random.seed(42)
N     = 10_000
MESES = 12

print("✅ Celda 1 lista")
print(f"   Simulaciones : {N:,}")
print(f"   Horizonte    : {MESES} meses")



# ══════════════════════════════════════════════════════════════════════════════
# CELDA 2 — CARGA DE DATOS REALES
# ══════════════════════════════════════════════════════════════════════════════

# ── ORO HISTÓRICO ─────────────────────────────────────────────────────────────
gold_hist          = pd.read_csv("gold_historical_prices.csv")
gold_hist['Date']  = pd.to_datetime(gold_hist['Date'])
gold_hist['price'] = gold_hist['Mid']
gold_hist          = gold_hist[['Date','price']].dropna().sort_values('Date')

gold_m         = gold_hist.set_index('Date').resample('ME').last()
gold_m['ret']  = np.log(gold_m['price'] / gold_m['price'].shift(1))
gold_m         = gold_m.dropna()

oro_vol_mensual = gold_m['ret'].std()
oro_vol_anual   = oro_vol_mensual * np.sqrt(12)
oro_spot        = gold_m['price'].iloc[-1]

print("── ORO HISTÓRICO ──")
print(f"   Spot actual    : ${oro_spot:,.2f}/oz")
print(f"   Vol mensual    : {oro_vol_mensual:.4f} ({oro_vol_mensual*100:.2f}%)")
print(f"   Vol anualizada : {oro_vol_anual:.4f} ({oro_vol_anual*100:.2f}%)")

# ── FUTUROS ORO → CURVA FORWARD ───────────────────────────────────────────────
gold_fut        = pd.read_csv("gold_forecasts.csv")
gold_fut['BID'] = pd.to_numeric(gold_fut['BID'], errors='coerce')
gold_fut['ASK'] = pd.to_numeric(gold_fut['ASK'], errors='coerce')
gold_fut['mid'] = (gold_fut['BID'] + gold_fut['ASK']) / 2

mes_map = {'F':1,'G':2,'H':3,'J':4,'K':5,'M':6,
           'N':7,'Q':8,'U':9,'V':10,'X':11,'Z':12}

futuros_oro = []
for _, row in gold_fut.iterrows():
    inst = str(row['Instrument'])
    if inst.startswith('/GC') and pd.notna(row['mid']) and len(inst) == 6:
        letra = inst[3]
        yr    = int('20' + inst[4:6])
        mes   = mes_map.get(letra)
        if mes:
            futuros_oro.append({
                'fecha' : pd.Timestamp(year=yr, month=mes, day=15),
                'precio': row['mid']
            })

df_fut_oro = pd.DataFrame(futuros_oro).sort_values('fecha').reset_index(drop=True)

fechas_horizonte      = pd.date_range('2026-06-01', periods=12, freq='MS')
precios_forward_oro   = np.interp(
    [f.timestamp() for f in fechas_horizonte],
    [f.timestamp() for f in df_fut_oro['fecha']],
    df_fut_oro['precio'].values
)
drift_oro_mensual = np.concatenate([
    [np.log(precios_forward_oro[0] / oro_spot)],
    np.diff(np.log(precios_forward_oro))
])

meses_nombres = ['Jun26','Jul26','Ago26','Sep26','Oct26','Nov26',
                 'Dic26','Ene27','Feb27','Mar27','Abr27','May27']

print(f"\n── FUTUROS ORO ──")
for nombre, precio in zip(meses_nombres, precios_forward_oro):
    print(f"   {nombre}: ${precio:,.1f}/oz")

# ── FX HISTÓRICO ──────────────────────────────────────────────────────────────
fx_hist          = pd.read_csv("usdmxn_historical_prices.csv")
fx_hist['Date']  = pd.to_datetime(fx_hist['Date'])
fx_hist['price'] = fx_hist['Mid']
fx_hist          = fx_hist[['Date','price']].dropna().sort_values('Date')

fx_m        = fx_hist.set_index('Date').resample('ME').last()
fx_m['ret'] = np.log(fx_m['price'] / fx_m['price'].shift(1))
fx_m        = fx_m.dropna()

fx_vol_mensual = fx_m['ret'].std()
fx_vol_anual   = fx_vol_mensual * np.sqrt(12)
fx_spot        = fx_m['price'].iloc[-1]

print(f"\n── FX HISTÓRICO ──")
print(f"   Spot actual    : {fx_spot:.4f} MXN/USD")
print(f"   Vol mensual    : {fx_vol_mensual:.4f} ({fx_vol_mensual*100:.2f}%)")
print(f"   Vol anualizada : {fx_vol_anual:.4f} ({fx_vol_anual*100:.2f}%)")

# ── FX FORWARDS ───────────────────────────────────────────────────────────────
swap_pts = {1: 0.0475, 3: 0.138, 6: 0.27, 12: 0.555}
meses_conocidos    = np.array([0] + list(swap_pts.keys()))
forwards_conocidos = np.array([fx_spot] + [fx_spot + p for p in swap_pts.values()])
forwards_fx_mensual = np.interp(np.arange(1, 13),
                                 meses_conocidos,
                                 forwards_conocidos)
drift_fx_mensual = np.concatenate([
    [np.log(forwards_fx_mensual[0] / fx_spot)],
    np.diff(np.log(forwards_fx_mensual))
])

print(f"\n── FX FORWARDS ──")
for nombre, fwd in zip(meses_nombres, forwards_fx_mensual):
    print(f"   {nombre}: {fwd:.4f} MXN/USD")

print("\n✅ Celda 2 lista")

# ══════════════════════════════════════════════════════════════════════════════
# CELDA 3 — PARÁMETROS ACTUALIZADOS
# Precio spot: $4,420/oz | Strike put: $4,200/oz | Prima: 5% strike
# ══════════════════════════════════════════════════════════════════════════════

# ── ESTADO DE RESULTADOS (anualizado 1T26) ────────────────────────────────────
ingresos_totales_1T26    = 98_386_000
ingresos_metallorum_1T26 = 11_964_000
ingresos_op_anual        = (ingresos_totales_1T26 -
                            ingresos_metallorum_1T26) * 4

costo_ventas_anual = 83_463_000 * 4
gastos_venta_anual = 5_905_000  * 4
gastos_admin_anual = 10_656_000 * 4
otros_gastos_anual = 1_808_000  * 4
depreciacion_anual = 10_597_000 * 4
capex_anual        = 3_313_000  * 4
tasa_isr           = 0.30

# ── EBITDA HISTÓRICO ──────────────────────────────────────────────────────────
ebitda_trimestral  = np.array([7_466, 7_873, 9_356, 6_777, 10_767])
ebitda_media_anual = ebitda_trimestral.mean() * 4 * 1_000
ebitda_std_anual   = ebitda_trimestral.std()  * 4 * 1_000

# ── DEUDA ─────────────────────────────────────────────────────────────────────
saldo_c1   = 119_000_000
saldo_c2   =  16_000_000
meses_c1   = 66
meses_c2   = 19
spread_c1  = 0.0600
spread_c2  = 0.0550
sofr_fijo  = 0.03593

# GAFIN referencias Kramsky
gafin_sin_ref = 34_129_000   # deuda variable toda
gafin_con_ref =  9_000_000   # solo deuda restante tras pagar mala

# ── PUT ORO — ACTUALIZADO ─────────────────────────────────────────────────────
onzas_cubiertas = 10_000
onzas_libres    = 10_000
strike_put      = 4_200.0    # ← precio piso
prima_por_oz    = 210.0      # ← 5% del strike $4,200
prima_put_total = onzas_cubiertas * prima_por_oz   # $2,100,000

# ── INGRESOS BASE ─────────────────────────────────────────────────────────────
ingresos_base = 98_386_000 * 4   # $393.6M incluye 20k oz

# ── PUT PESO ──────────────────────────────────────────────────────────────────
prima_put_peso = ingresos_base * 0.60 * 0.05   # 5% de costos MXN

# Horizonte
N_MESES = 7   # jun-dic 2026

print("── PARÁMETROS ACTUALIZADOS ──")
print(f"\n   PUT ORO:")
print(f"   Precio spot actual        : $4,420/oz  ← actualizado")
print(f"   Strike (precio piso)      : ${strike_put:,.0f}/oz  ← actualizado")
print(f"   Prima (5% del strike)     : ${prima_por_oz:.0f}/oz")
print(f"   Prima total               : ${prima_put_total/1e6:.2f}M")
print(f"\n   Verificación Kramsky:")
print(f"   10,000 × ${strike_put:,.0f} - ${prima_put_total/1e6:.2f}M = "
      f"${(onzas_cubiertas*strike_put - prima_put_total)/1e6:.2f}M")
print(f"   Kramsky obtuvo            : $39,900,000 "
      f"{'✅' if abs(onzas_cubiertas*strike_put - prima_put_total - 39_900_000) < 1000 else '❌'}")

print(f"\n   DEUDA:")
print(f"   SOFR fijado hoy           : {sofr_fijo:.3%}")
print(f"   Crédito 1 (SOFR+6%)       : ${saldo_c1/1e6:.0f}M")
print(f"   Crédito 2 (SOFR+5.5%)     : ${saldo_c2/1e6:.0f}M")
print(f"   GAFIN sin cobertura ref.  : ${gafin_sin_ref/1e6:.3f}M")
print(f"   GAFIN con cobertura ref.  : ${gafin_con_ref/1e6:.0f}M")

print(f"\n   INGRESOS BASE:")
print(f"   Ingresos totales (×4)     : ${ingresos_base/1e6:.1f}M")
print(f"   Prima put peso (5% costos): ${prima_put_peso/1e6:.3f}M")

print("\n✅ Celda 3 lista")

# ══════════════════════════════════════════════════════════════════════════════
# CELDA 4 — SERIES DE TIEMPO CON SPOT ACTUALIZADO
# Precio spot oro: $4,420/oz
# ══════════════════════════════════════════════════════════════════════════════

np.random.seed(42)

# ── ORO — spot actualizado a $4,420 ──────────────────────────────────────────
oro_spot        = 4_420.0    # ← precio actual que defines

oro_sim         = np.zeros((N, MESES))
precio_anterior = np.full(N, oro_spot)

for m in range(MESES):
    Z               = np.random.normal(0, 1, N)
    oro_sim[:, m]   = precio_anterior * np.exp(
        drift_oro_mensual[m] - 0.5 * oro_vol_mensual**2 + oro_vol_mensual * Z
    )
    precio_anterior = oro_sim[:, m]

oro_año = oro_sim[:, -1]

print("── ORO SIMULADO ──")
print(f"   Spot inicial (actualizado): ${oro_spot:,.2f}/oz  ← $4,420")
print(f"   Strike put                : ${strike_put:,.0f}/oz")
print(f"   Forward May-27            : ${precios_forward_oro[-1]:,.2f}/oz")
print(f"   Media simulada            : ${oro_año.mean():,.2f}/oz")
print(f"   P5                        : ${np.percentile(oro_año,5):,.2f}/oz")
print(f"   P50                       : ${np.percentile(oro_año,50):,.2f}/oz")
print(f"   P95                       : ${np.percentile(oro_año,95):,.2f}/oz")
print(f"   Put ejercido (< ${strike_put:,.0f})  : "
      f"{(oro_año < strike_put).sum():,} "
      f"({(oro_año < strike_put).mean():.1%})")

# ── FX — sin cambios ──────────────────────────────────────────────────────────
fx_sim      = np.zeros((N, MESES))
fx_anterior = np.full(N, fx_spot)

for m in range(MESES):
    Z             = np.random.normal(0, 1, N)
    fx_sim[:, m]  = fx_anterior * np.exp(
        drift_fx_mensual[m] - 0.5 * fx_vol_mensual**2 + fx_vol_mensual * Z
    )
    fx_anterior   = fx_sim[:, m]

fx_año = fx_sim[:, -1]

print(f"\n── FX SIMULADO ──")
print(f"   Spot actual               : {fx_spot:.4f} MXN/USD")
print(f"   Media simulada            : {fx_año.mean():.4f} MXN/USD")
print(f"   P5                        : {np.percentile(fx_año,5):.4f}")
print(f"   P95                       : {np.percentile(fx_año,95):.4f}")

# ── SOFR — Vasicek sin cambios ────────────────────────────────────────────────
sofr_kappa    = 0.30
sofr_theta    = 0.035
sofr_sigma_r  = 0.010
sofr_dt       = 1/12
sofr_actual   = 0.03593

sofr_sim      = np.zeros((N, MESES))
sofr_anterior = np.full(N, sofr_actual)

for m in range(MESES):
    Z             = np.random.normal(0, 1, N)
    sofr_sim[:,m] = (sofr_anterior
                     + sofr_kappa * (sofr_theta - sofr_anterior) * sofr_dt
                     + sofr_sigma_r * np.sqrt(sofr_dt) * Z)
    sofr_sim[:,m] = np.clip(sofr_sim[:,m], 0.001, 0.15)
    sofr_anterior = sofr_sim[:, m]

sofr_prom = sofr_sim.mean(axis=1)

print(f"\n── SOFR SIMULADO ──")
print(f"   SOFR fijado IRS           : {sofr_fijo:.3%}")
print(f"   SOFR mercado P50          : {np.percentile(sofr_prom,50):.2%}")
print(f"   SOFR mercado P95          : {np.percentile(sofr_prom,95):.2%}")

print(f"\n✅ Celda 4 lista")
print(f"   oro_sim  : {oro_sim.shape}")
print(f"   fx_sim   : {fx_sim.shape}")
print(f"   sofr_sim : {sofr_sim.shape}")

# ══════════════════════════════════════════════════════════════════════════════
# CELDA 5 — CASCADA + ESTADO DE RESULTADOS
# Strike: $4,200 | Prima: $210/oz | Spot: $4,420
# ══════════════════════════════════════════════════════════════════════════════

oro_año  = oro_sim[:, -1]
fx_año   = fx_sim[:, -1]

# ══════════════════════════════════════════════════════════════════════════════
# CASCADA — GENERA EL REMANENTE
# ══════════════════════════════════════════════════════════════════════════════

def pago_fijo(saldo, meses_total, sofr, spread, n):
    cuota   = saldo / meses_total
    tasa_m  = (sofr + spread) / 12
    total   = 0.0
    saldo_m = float(saldo)
    for _ in range(n):
        total  += saldo_m * tasa_m + cuota
        saldo_m -= cuota
    return total

def pago_variable(saldo, meses_total, sofr_vec, spread, n):
    cuota   = saldo / meses_total
    tasa_m  = (sofr_vec + spread) / 12
    total   = np.zeros(N)
    saldo_m = np.full(N, float(saldo))
    for _ in range(n):
        total  += saldo_m * tasa_m + cuota
        saldo_m -= cuota
    return total

# ── Paso 1: Put oro ───────────────────────────────────────────────────────────
ingreso_oz_cub  = np.where(
    oro_año < strike_put,
    onzas_cubiertas * strike_put,
    onzas_cubiertas * oro_año
)
ingreso_neto_p1 = ingreso_oz_cub - prima_put_total

# ── Paso 2: IRS ───────────────────────────────────────────────────────────────
pago_c1_fijo    = pago_fijo(
    saldo_c1, meses_c1, sofr_fijo, spread_c1, N_MESES)
pago_c2_fijo    = pago_fijo(
    saldo_c2, meses_c2, sofr_fijo, spread_c2, N_MESES)
pago_deuda_fijo = pago_c1_fijo + pago_c2_fijo

pago_c1_var     = pago_variable(
    saldo_c1, meses_c1, sofr_prom, spread_c1, N_MESES)
pago_c2_var     = pago_variable(
    saldo_c2, meses_c2, sofr_prom, spread_c2, N_MESES)
pago_deuda_var  = pago_c1_var + pago_c2_var

prima_swap_sim  = pago_deuda_var - pago_deuda_fijo
remanente_p2    = ingreso_neto_p1 - prima_swap_sim - pago_deuda_fijo

# ── Paso 3: Put peso ──────────────────────────────────────────────────────────
remanente_cascada = remanente_p2 - prima_put_peso

pasa_fase1 = np.ones(N, dtype=bool)
pasa_fase2 = remanente_p2 >= 0
pasa_fase3 = remanente_cascada >= 0
pasa_todo  = pasa_fase1 & pasa_fase2 & pasa_fase3

print("── CASCADA ──")
print(f"   Paso 1 ingreso neto mín.  : "
      f"${ingreso_neto_p1.min()/1e6:.2f}M")
print(f"   Paso 1 ingreso neto prom. : "
      f"${ingreso_neto_p1.mean()/1e6:.2f}M")
print(f"   Verificación: 10k×$4,200-$2.1M = "
      f"${(onzas_cubiertas*strike_put-prima_put_total)/1e6:.2f}M ✅")
print(f"   Paso 2 pago deuda fijo    : ${pago_deuda_fijo/1e6:.3f}M")
print(f"   Paso 2 prima swap prom.   : ${prima_swap_sim.mean()/1e6:.3f}M")
print(f"   Paso 2 remanente prom.    : ${remanente_p2.mean()/1e6:.2f}M")
print(f"   Paso 2 remanente mín.     : ${remanente_p2.min()/1e6:.2f}M")
print(f"   Kramsky obtuvo            : $14.184M")
print(f"   Paso 3 prima put peso     : ${prima_put_peso/1e6:.3f}M")
print(f"   Remanente cascada prom.   : ${remanente_cascada.mean()/1e6:.2f}M")
print(f"   Remanente cascada mín.    : ${remanente_cascada.min()/1e6:.2f}M")
print(f"   Kramsky peor escenario    : ~$2.38M")

# ══════════════════════════════════════════════════════════════════════════════
# ESTADO DE RESULTADOS — SIN COBERTURA
# ══════════════════════════════════════════════════════════════════════════════

precio_oro_base    = 4_420.0
ingreso_oz_base    = (onzas_cubiertas + onzas_libres) * precio_oro_base
ingreso_oz_sim     = (onzas_cubiertas + onzas_libres) * oro_año
ajuste_oro_sin     = ingreso_oz_sim - ingreso_oz_base

ingresos_sin_cob   = ingresos_base + ajuste_oro_sin
gastos_op_sin      = ingresos_sin_cob * 0.60
ebit_sin           = ingresos_sin_cob - gastos_op_sin

ajuste_gafin_sin   = (sofr_prom - 0.0386) * (saldo_c1 + saldo_c2)
gafin_sin_sim      = gafin_sin_ref + ajuste_gafin_sin

ebt_sin            = ebit_sin - gafin_sin_sim
isr_sin            = np.where(ebt_sin > 0, ebt_sin * tasa_isr, 0)
fcf_sin_cob        = ebt_sin - isr_sin

# ══════════════════════════════════════════════════════════════════════════════
# ESTADO DE RESULTADOS — CON COBERTURA
# ══════════════════════════════════════════════════════════════════════════════

ingreso_oz_lib_sim = onzas_libres * oro_año
ingreso_oz_lib_base = onzas_libres * precio_oro_base
ajuste_oro_con     = ingreso_oz_lib_sim - ingreso_oz_lib_base

ingresos_con_cob   = (ingresos_base -
                      onzas_cubiertas * precio_oro_base) + ajuste_oro_con
gastos_op_con      = ingresos_con_cob * 0.60
ebit_con           = ingresos_con_cob - gastos_op_con

gafin_con_sim      = np.full(N, float(gafin_con_ref))

ebt_con            = ebit_con - gafin_con_sim
isr_con            = np.where(ebt_con > 0, ebt_con * tasa_isr, 0)
fcf_operativo_con  = ebt_con - isr_con

fcf_con_cob        = fcf_operativo_con + remanente_cascada
diferencia_fcf     = fcf_con_cob - fcf_sin_cob

# ══════════════════════════════════════════════════════════════════════════════
# RESUMEN
# ══════════════════════════════════════════════════════════════════════════════
print(f"\n{'═'*65}")
print(f"  ESTADO DE RESULTADOS — ESCENARIO BASE")
print(f"  Strike: $4,200 | Prima: $210/oz | Spot: $4,420")
print(f"{'═'*65}")
print(f"  {'Concepto':<32} {'Sin Cob':>14} {'Con Cob':>14}")
print(f"  {'─'*62}")

for concepto, s, c in [
    ("Ingresos totales",
     ingresos_sin_cob.mean(), ingresos_con_cob.mean()),
    ("- Gastos op. (60%)",
     gastos_op_sin.mean(),    gastos_op_con.mean()),
    ("EBIT",
     ebit_sin.mean(),         ebit_con.mean()),
    ("- GAFIN",
     gafin_sin_sim.mean(),    gafin_con_sim.mean()),
    ("EBT",
     ebt_sin.mean(),          ebt_con.mean()),
    ("- ISR (30%)",
     isr_sin.mean(),          isr_con.mean()),
    ("FCF operativo",
     fcf_sin_cob.mean(),      fcf_operativo_con.mean()),
    ("+ Remanente cascada",
     0,                       remanente_cascada.mean()),
    ("FCF TOTAL",
     fcf_sin_cob.mean(),      fcf_con_cob.mean()),
]:
    es_total = "FCF TOTAL" in concepto
    print(f"  {concepto:<32} "
          f"${s/1e6:>12.2f}M "
          f"${c/1e6:>12.2f}M"
          f"{'  ←' if es_total else ''}")

print(f"\n  {'─'*62}")
print(f"  {'DIFERENCIA (con - sin)':<32} "
      f"{'':>14} "
      f"${diferencia_fcf.mean()/1e6:>+12.2f}M")
print(f"  Kramsky calculó: ~$7M")

print(f"\n{'═'*65}")
print(f"  CONTEO DE ESCENARIOS")
print(f"{'═'*65}")
print(f"  Pasan Paso 1 (Put oro)     : "
      f"{pasa_fase1.sum():,} ({pasa_fase1.mean():.1%})")
print(f"  Pasan Paso 2 (IRS+deuda)   : "
      f"{pasa_fase2.sum():,} ({pasa_fase2.mean():.1%})")
print(f"  Pasan Paso 3 (Remanente≥0) : "
      f"{pasa_fase3.sum():,} ({pasa_fase3.mean():.1%})")
print(f"  Pasan los 3 pasos          : "
      f"{pasa_todo.sum():,} ({pasa_todo.mean():.1%})")

print(f"\n{'═'*65}")
print(f"  FCF TOTAL — DISTRIBUCIÓN")
print(f"{'═'*65}")
print(f"  {'Métrica':<20} {'Sin Cob':>12} {'Con Cob':>12} "
      f"{'Diferencia':>12}")
print(f"  {'─'*58}")

for label, s, c in [
    ("Media",   fcf_sin_cob.mean(),
                fcf_con_cob.mean()),
    ("Mínimo",  fcf_sin_cob.min(),
                fcf_con_cob.min()),
    ("P5",      np.percentile(fcf_sin_cob, 5),
                np.percentile(fcf_con_cob, 5)),
    ("P25",     np.percentile(fcf_sin_cob, 25),
                np.percentile(fcf_con_cob, 25)),
    ("Mediana", np.percentile(fcf_sin_cob, 50),
                np.percentile(fcf_con_cob, 50)),
    ("P75",     np.percentile(fcf_sin_cob, 75),
                np.percentile(fcf_con_cob, 75)),
    ("P95",     np.percentile(fcf_sin_cob, 95),
                np.percentile(fcf_con_cob, 95)),
    ("Máximo",  fcf_sin_cob.max(),
                fcf_con_cob.max()),
]:
    diff  = c - s
    emoji = "✅" if diff > 0 else "⚠️"
    print(f"  {label:<20} "
          f"${s/1e6:>10.2f}M "
          f"${c/1e6:>10.2f}M "
          f"${diff/1e6:>+10.2f}M {emoji}")

print(f"\n  FCF>0 sin cobertura : {(fcf_sin_cob>0).mean():.1%}")
print(f"  FCF>0 con cobertura : {(fcf_con_cob>0).mean():.1%}")
print(f"  Diferencia promedio : +${diferencia_fcf.mean()/1e6:.2f}M")
print(f"  Kramsky calculó     : ~$7M")

print("\n✅ Celda 5 lista — strike $4,200 | spot $4,420")

# ══════════════════════════════════════════════════════════════════════════════
# CELDA 6 — GRÁFICAS FINALES CON RANGO P5-P95
# ══════════════════════════════════════════════════════════════════════════════

fig = plt.figure(figsize=(18, 14))
fig.suptitle(
    'Simulación Monte Carlo — Compañía Minera Autlán\n'
    'Estrategia Integral de Cobertura: Put Oro + IRS + Put Peso\n'
    'Horizonte: Jun–Dic 2026 | N = 10,000 escenarios | '
    'Strike: $4,200/oz | Spot: $4,420/oz',
    fontsize=12, fontweight='bold', y=0.98
)

C_SIN  = '#C0392B'
C_CON  = '#1E6B3C'
C_ORO  = '#C9A84C'
C_FASE = '#2E75B6'
GRIS   = '#7F8C8D'

# Percentiles clave
p5_sin  = np.percentile(fcf_sin_cob, 5)
p50_sin = np.percentile(fcf_sin_cob, 50)
p95_sin = np.percentile(fcf_sin_cob, 95)
p5_con  = np.percentile(fcf_con_cob, 5)
p50_con = np.percentile(fcf_con_cob, 50)
p95_con = np.percentile(fcf_con_cob, 95)

p5_dif  = np.percentile(diferencia_fcf, 5)
p50_dif = np.percentile(diferencia_fcf, 50)
p95_dif = np.percentile(diferencia_fcf, 95)

# ══════════════════════════════════════════════════════════════════════════════
# GRÁFICA 1 — EMBUDO DE FASES
# ══════════════════════════════════════════════════════════════════════════════
ax1 = fig.add_subplot(2, 2, 1)

pasos   = ['Total\n10,000', 'Paso 1\nPut Oro',
           'Paso 2\nIRS+Deuda', 'Paso 3\nRemanente≥0']
valores = [N, pasa_fase1.sum(), pasa_fase2.sum(), pasa_fase3.sum()]
pcts    = [v/N*100 for v in valores]
colores = ['#1F3864', C_ORO, C_FASE, C_CON]

bars = ax1.bar(pasos, valores, color=colores,
               alpha=0.85, edgecolor='white',
               linewidth=1.5, width=0.55)

for bar, v, p in zip(bars, valores, pcts):
    ax1.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 80,
             f'{v:,}\n({p:.1f}%)',
             ha='center', va='bottom',
             fontsize=10, fontweight='bold')

ax1.set_title('Escenarios que Pasan Cada Paso\n'
              'Embudo de la Cascada',
              fontweight='bold', fontsize=11)
ax1.set_ylabel('Número de escenarios')
ax1.set_ylim(0, 12_500)
ax1.yaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x,_: f'{x:,.0f}'))
ax1.set_facecolor('#FAFAFA')

ax1.text(0.5, 0.06,
         f'100% escenarios pasan las 3 fases\n'
         f'Remanente mínimo: '
         f'${remanente_cascada.min()/1e6:.2f}M | '
         f'Kramsky: ~$2.38M',
         transform=ax1.transAxes, ha='center',
         fontsize=8, style='italic', color=C_CON,
         bbox=dict(boxstyle='round',
                   facecolor='#E8F5E9', alpha=0.8))

# ══════════════════════════════════════════════════════════════════════════════
# GRÁFICA 2 — CAMPANA FCF (P5-P95)
# ══════════════════════════════════════════════════════════════════════════════
ax2 = fig.add_subplot(2, 2, 2)

# Filtrar al rango P5-P95 para la visualización
mask_sin = (fcf_sin_cob >= p5_sin) & (fcf_sin_cob <= p95_sin)
mask_con = (fcf_con_cob >= p5_con) & (fcf_con_cob <= p95_con)

ax2.hist(fcf_sin_cob[mask_sin]/1e6, bins=60,
         alpha=0.5, color=C_SIN, density=True,
         label='Sin cobertura (P5–P95)')
ax2.hist(fcf_con_cob[mask_con]/1e6, bins=60,
         alpha=0.6, color=C_CON, density=True,
         label='Con cobertura (P5–P95)')

# Medianas
ax2.axvline(p50_sin/1e6, color=C_SIN,
            linestyle='--', linewidth=2,
            label=f'Mediana sin: ${p50_sin/1e6:.1f}M')
ax2.axvline(p50_con/1e6, color=C_CON,
            linestyle='--', linewidth=2,
            label=f'Mediana con: ${p50_con/1e6:.1f}M')

# Bandas P5-P95
ax2.axvspan(p5_sin/1e6, p95_sin/1e6,
            alpha=0.05, color=C_SIN)
ax2.axvspan(p5_con/1e6, p95_con/1e6,
            alpha=0.05, color=C_CON)

ax2.set_title('Campana FCF Total — Rango P5–P95\n'
              'Con vs Sin Cobertura',
              fontweight='bold', fontsize=11)
ax2.set_xlabel('FCF Total (millones USD)')
ax2.set_ylabel('Densidad')
ax2.legend(fontsize=8)
ax2.xaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x,_: f'${x:.0f}M'))
ax2.set_facecolor('#FAFAFA')

# Tabla estadísticas
stats_text = (
    f"Rango P5–P95:\n"
    f"Sin cob: ${p5_sin/1e6:.0f}M – ${p95_sin/1e6:.0f}M\n"
    f"Con cob: ${p5_con/1e6:.0f}M – ${p95_con/1e6:.0f}M\n"
    f"Mejora mediana: +${(p50_con-p50_sin)/1e6:.1f}M\n"
    f"FCF>0: 100% con cobertura"
)
ax2.text(0.02, 0.97, stats_text,
         transform=ax2.transAxes,
         ha='left', va='top', fontsize=8,
         bbox=dict(boxstyle='round',
                   facecolor='lightyellow', alpha=0.8))

# ══════════════════════════════════════════════════════════════════════════════
# GRÁFICA 3 — DISTRIBUCIÓN DE LA MEJORA (DIFERENCIA FCF)
# ══════════════════════════════════════════════════════════════════════════════
ax3 = fig.add_subplot(2, 2, 3)

# Solo rango P5-P95 de la diferencia
mask_dif = (diferencia_fcf >= p5_dif) & (diferencia_fcf <= p95_dif)

ax3.hist(diferencia_fcf[mask_dif]/1e6, bins=60,
         alpha=0.75, color=C_FASE, density=True,
         label='Mejora FCF (P5–P95)')

# Líneas de referencia
ax3.axvline(p5_dif/1e6, color=GRIS,
            linestyle=':', linewidth=2,
            label=f'P5: +${p5_dif/1e6:.1f}M')
ax3.axvline(p50_dif/1e6, color='black',
            linestyle='--', linewidth=2,
            label=f'Mediana: +${p50_dif/1e6:.1f}M')
ax3.axvline(p95_dif/1e6, color=GRIS,
            linestyle=':', linewidth=2,
            label=f'P95: +${p95_dif/1e6:.1f}M')

# Zona Kramsky ($8M-$20M)
ax3.axvspan(8, 20, alpha=0.15, color=C_CON,
            label='Rango Kramsky ($8M–$20M)')

ax3.set_title('Distribución de la Mejora en FCF\n'
              'Con Cobertura vs Sin Cobertura (P5–P95)',
              fontweight='bold', fontsize=11)
ax3.set_xlabel('Mejora en FCF (millones USD)')
ax3.set_ylabel('Densidad')
ax3.legend(fontsize=8)
ax3.xaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x,_: f'+${x:.0f}M'))
ax3.set_facecolor('#FAFAFA')

# Anotación Kramsky
ax3.text(0.5, 0.90,
         f'P5={p5_dif/1e6:.1f}M | '
         f'Mediana={p50_dif/1e6:.1f}M | '
         f'P95={p95_dif/1e6:.1f}M\n'
         f'Rango Kramsky: $8M–$20M ✅',
         transform=ax3.transAxes,
         ha='center', va='top', fontsize=9,
         fontweight='bold', color=C_CON,
         bbox=dict(boxstyle='round',
                   facecolor='#E8F5E9', alpha=0.8))

# ══════════════════════════════════════════════════════════════════════════════
# GRÁFICA 4 — ESTADO DE RESULTADOS COMPARATIVO EN BARRAS
# ══════════════════════════════════════════════════════════════════════════════
ax4 = fig.add_subplot(2, 2, 4)

conceptos_bar = ['Ingresos', 'Gastos\nOp.', 'EBIT',
                 'GAFIN', 'ISR', 'FCF\nOp.',
                 'Remanente\nCascada', 'FCF\nTotal']

valores_sin = [
    ingresos_sin_cob.mean()/1e6,
    gastos_op_sin.mean()/1e6,
    ebit_sin.mean()/1e6,
    gafin_sin_sim.mean()/1e6,
    isr_sin.mean()/1e6,
    fcf_sin_cob.mean()/1e6,
    0,
    fcf_sin_cob.mean()/1e6,
]
valores_con = [
    ingresos_con_cob.mean()/1e6,
    gastos_op_con.mean()/1e6,
    ebit_con.mean()/1e6,
    gafin_con_sim.mean()/1e6,
    isr_con.mean()/1e6,
    fcf_operativo_con.mean()/1e6,
    remanente_cascada.mean()/1e6,
    fcf_con_cob.mean()/1e6,
]

x     = np.arange(len(conceptos_bar))
width = 0.35

bars_sin = ax4.bar(x - width/2, valores_sin, width,
                    label='Sin cobertura',
                    color=C_SIN, alpha=0.75,
                    edgecolor='white')
bars_con = ax4.bar(x + width/2, valores_con, width,
                    label='Con cobertura',
                    color=C_CON, alpha=0.75,
                    edgecolor='white')

for bar in list(bars_sin) + list(bars_con):
    h = bar.get_height()
    if h > 8:
        color = C_SIN if bar in bars_sin else C_CON
        ax4.text(bar.get_x() + bar.get_width()/2,
                 h + 1.5, f'${h:.0f}M',
                 ha='center', va='bottom',
                 fontsize=7, color=color,
                 fontweight='bold')

ax4.set_title('Estado de Resultados — Comparativo\n'
              f'Mejora FCF mediana: '
              f'+${p50_dif/1e6:.1f}M '
              f'| Rango P5–P95: '
              f'+${p5_dif/1e6:.0f}M a '
              f'+${p95_dif/1e6:.0f}M',
              fontweight='bold', fontsize=11)
ax4.set_ylabel('Millones USD')
ax4.set_xticks(x)
ax4.set_xticklabels(conceptos_bar, fontsize=8)
ax4.legend(fontsize=9)
ax4.yaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x,_: f'${x:.0f}M'))
ax4.set_facecolor('#FAFAFA')

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('montecarlo_autlan_final.png',
            dpi=150, bbox_inches='tight')
plt.show()

# ── RESUMEN EJECUTIVO FINAL ───────────────────────────────────────────────────
print("\n" + "═"*65)
print("  RESUMEN EJECUTIVO — MONTE CARLO AUTLÁN")
print("  Strike: $4,200/oz | Prima: $210/oz | Spot: $4,420/oz")
print("  Horizonte: Jun–Dic 2026 | N = 10,000 escenarios")
print("═"*65)

print(f"\n  CASCADA (peor escenario):")
print(f"  Paso 1 ingreso neto mín.  : $39.90M ✅ (Kramsky: $39.90M)")
print(f"  Paso 2 remanente mín.     : ${remanente_p2.min()/1e6:.2f}M")
print(f"  Paso 3 remanente casc.mín.: ${remanente_cascada.min()/1e6:.2f}M")
print(f" : ~$2.38M")

print(f"\n  ESTADO DE RESULTADOS (promedio):")
print(f"  {'Concepto':<25} {'Sin Cob':>10} {'Con Cob':>10}")
print(f"  {'─'*48}")
for concepto, s, c in [
    ("Ingresos",      ingresos_sin_cob.mean(), ingresos_con_cob.mean()),
    ("Gastos op(60%)",gastos_op_sin.mean(),    gastos_op_con.mean()),
    ("EBIT",          ebit_sin.mean(),          ebit_con.mean()),
    ("GAFIN",         gafin_sin_sim.mean(),     gafin_con_sim.mean()),
    ("ISR (30%)",     isr_sin.mean(),           isr_con.mean()),
    ("FCF operativo", fcf_sin_cob.mean(),       fcf_operativo_con.mean()),
    ("Remanente casc.",0,                       remanente_cascada.mean()),
    ("FCF TOTAL",     fcf_sin_cob.mean(),       fcf_con_cob.mean()),
]:
    print(f"  {concepto:<25} "
          f"${s/1e6:>8.1f}M "
          f"${c/1e6:>8.1f}M")

print(f"\n  MEJORA FCF (rango P5–P95):")
print(f"  P5  (escenarios adversos) : +${p5_dif/1e6:.1f}M")
print(f"  P50 (escenario típico)    : +${p50_dif/1e6:.1f}M")
print(f"  P95 (escenarios favorab.) : +${p95_dif/1e6:.1f}M")
print(f"$8M – $20M ✅")

print(f"\n  ESCENARIOS:")
print(f"  Pasan los 3 pasos : {pasa_todo.mean():.1%}")
print(f"  FCF>0 sin cob     : {(fcf_sin_cob>0).mean():.1%}")
print(f"  FCF>0 con cob     : {(fcf_con_cob>0).mean():.1%}")

print("\n✅ Análisis Monte Carlo completo")